### ISSUE TITLE
could not support file operation in python

### ISSUE THREAD

**Issue by fzwwj95** [exaloop/codon#341] opened 2023-04-09 05:04 UTC
I use the code " with open (...) as file: "
codon could not support and report an error : " error: syntax error ,unexpected 'as'  "

**Comment by elisbyberi** [comment] 2023-04-09 12:37
@fzwwj95 

Please test this code and let me know what errors you encounter:
``` python
with open('codon.test', 'w') as w:
    w.write('test')

with open('codon.test') as r:
    print(r.read())
```

**Comment by fzwwj95** [comment] 2023-04-10 13:26
I tested both pieces of code separately, and both gave the same error : " error: syntax error ,unexpected 'as' "

**Comment by elisbyberi** [comment] 2023-04-10 15:10
@fzwwj95 Did you test it in Python?

**Comment by elisbyberi** [comment] 2023-04-11 17:31
@fzwwj95 Duplicate of #317

**Closed** 2023-04-13 02:16 UTC
