### ISSUE TITLE
Problem building jupyter plugin

### ISSUE THREAD

**Issue by orion160** [exaloop/codon#600] opened 2024-10-14 15:36 UTC
Environment:

- Fedora 40
- clang 18.1.8
- cmake 3.28.2

Configure command:

```bash
git clone --depth 1 -b v0.17.0 https://github.com/exaloop/codon.git
cmake -S codon/jupyter -B codon/jupyter_build -G Ninja \
-D CMAKE_BUILD_TYPE=Release \
-D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ \
-D CMAKE_CXX_FLAGS="-stdlib=libc++" \
-D LLVM_DIR=$(llvm-codon/install/bin/llvm-config --cmakedir) \
-D CODON_PATH=$($pwd)codon/install \
-D OPENSSL_ROOT_DIR=$(openssl version -d | cut -d' ' -f2 | tr -d '"') \
-D OPENSSL_CRYPTO_LIBRARY=/usr/lib64/libssl.so \
-D XEUS_USE_DYNAMIC_UUID=ON
```

Build

```
cmake --build codon/jupyter_build -j $(nproc)
```

Tried with libstdc++ and libc++

[jupyter_build.log](https://github.com/user-attachments/files/17366269/jupyter_build.log)

**Comment by inumanag** [comment] 2024-11-10 19:28
Duplicate of #152—moving the discussion there.

**Closed by inumanag** 2024-11-10 19:28 UTC
