### ISSUE TITLE
 error: syntax error, unexpected 'and'

### ISSUE THREAD

**Issue by starbugs-qurong** [exaloop/codon#323] opened 2023-04-04 10:37 UTC
I have run the following python program program3.py by codon.

class g32Ck29 (): 
	l618xA2v = "IXgotDE13"
	JR2F7RH5o = "r"
	ZPs35284 = 0.5
	vggx3vQ3 = 0.31
	def Q0400A8 ( self , M1595y67A : int , Zxd3V4Yw : int , wxUjz87u : int ) -> bool : 
			if (((self.l618xA2v)==None)and(self.JR2F7RH5o)==("V_J9S2w_UA")) : 
				self.ZPs35284+=self.vggx3vQ3  
if __name__ == '__main__':
	u3hZC2EfI = 2564
	s05PK59Exs = 1522
	PYMX80c = 7030
	OAD7y28949= g32Ck29();
	OAD7y28949.Q0400A8(u3hZC2EfI,s05PK59Exs,PYMX80c)
	print(OAD7y28949.ZPs35284)

And it output error message as follow:
codon_program3.py:7:31: error: syntax error, unexpected 'and'

I hava run it by both python3 and pypy3 and output the following content:
0.5

The related files can be found in https://github.com/starbugs-qurong/python-compiler-test/tree/main/codon/python_3

**Comment by elisbyberi** [comment] 2023-04-04 11:25
@starbugs-qurong Same as in #322, and you have to use type hint `Optional[str]`, if class member `l618xA2v` is going to be `None`.
``` python
class g32Ck29:
    l618xA2v: Optional[str] = "IXgotDE13"
```

**Comment by starbugs-qurong** [comment] 2023-04-11 10:19
Same as in #322 , spaces  must be added before and after the keyword "and". I have roughly read the rules of Whitespace in Expressions and Statements in [PEP 8](https://peps.python.org/pep-0008/)  and didn't find the explanation of “or” and "and".

**Comment by elisbyberi** [comment] 2023-04-11 17:30
@starbugs-qurong Duplicate of #317

**Comment by elisbyberi** [comment] 2023-04-14 11:38
@starbugs-qurong See PEP 8 [Other Recommendations](https://peps.python.org/pep-0008/#other-recommendations).

> Always surround these binary operators with a single space on either side: assignment (=), augmented assignment (+=, -= etc.), comparisons (==, <, >, !=, <>, <=, >=, in, not in, is, is not), Booleans (**and**, **or**, **not**).

**Comment by inumanag** [comment] 2024-11-09 20:25
Duplicate of #321.

**Closed** 2024-11-26 17:54 UTC
Labels: bug
