### ISSUE TITLE
codon-jit: No module named "codon"

### ISSUE THREAD

**Issue by matroscoe** [exaloop/codon#348] opened 2023-04-14 15:42 UTC
was hoping someone could help out with the following error: 
```
codon.codon_jit.JITError: /home/ubuntu/.pyenv/versions/3.11.1/envs/<venv>/lib/python3.11/site-packages/<internal-package>/file.py:19:2: no module named 'codon' 
```

I am using pycharm and in the editor it is not throwing any errors and `codon-jit` is in the venv I can find `codon/` and `codon_jit-0.1.3.dist-info` the issue only pops up when I try to kick off the python script importing our internal package which is developed and deployed with the `codon-jit` package listed as a dependency.

**Comment by yincangshiwei** [comment] 2023-06-05 08:16
I have the same situation, have you resolved it?

**Comment by matroscoe** [comment] 2023-06-05 15:38
@yincangshiwei no and I reached out both here and on the codon slack and got nothing in response so I don't know what to do about it.

**Comment by arshajii** [comment] 2023-06-05 15:41
Apologies for the delay. Let us look into this and follow up ASAP.

**Comment by pouyehbnj** [comment] 2024-03-26 15:34
I have the same issue. I'm using venv and codon-jit is installed there and I set ```CODON_PATH``` accordingly as well. I get the error :```no module named 'codon'``` . I tried it on a simple code from the documentation for prime number calculation and it did not work. However, codon itself works and I can access libraries using ```from python import``` . Is there any solution for this?

**Comment by inumanag** [comment] 2024-11-09 20:29
Duplicate of #123, moving the discussion there. Thank you all for these reports.

**Closed as completed by inumanag** 2024-11-09 20:29 UTC
