### ISSUE TITLE
Symbols not found error on small gpu example

### ISSUE THREAD

**Issue by dogbert45** [exaloop/codon#445] opened 2023-08-08 12:57 UTC
While trying the small gpu example below (from your doc) and running with _'codon run -release guptest.py'_
I end up with the following error:

_JIT session error: Symbols not found: [ seq_nvptx_memcpy_d2h, seq_nvptx_device_free, seq_nvptx_memcpy_h2d, seq_nvptx_invoke, seq_nvptx_load_module, seq_nvptx_device_alloc, seq_nvptx_function ]
Failure value returned from cantFail wrapped call
Failed to materialize symbols: { (main, { main, hello:0[std.internal.types.ptr.List[int],std.internal.types.ptr.List[int],std.internal.types.ptr.List[int]] }) }
UNREACHABLE executed at /github/workspace/llvm/include/llvm/Support/Error.h:786!
Aborted (core dumped)_

I have also tried with an older libdevice.10.bc but with same result.
This was with codon rel v0.16.2
I have an Nvida device : GeForce RTX 3060 Ti and is using 535.86.10 driver version.
Or do I need some command line switch for the gpu code to work?

import gpu

@gpu.kernel
def hello(a, b, c):
    i = gpu.thread.x
    c[i] = a[i] + b[i]

a = [i for i in range(16)]
b = [2*i for i in range(16)]
c = [0 for _ in range(16)]

hello(a, b, c, grid=1, block=16)
print(c)

**Comment by elisbyberi** [comment] 2023-08-08 21:47
Duplicate of #336

**Comment by inumanag** [comment] 2024-11-10 06:28
Duplicate of #193.

**Closed by inumanag** 2024-11-10 06:28 UTC
