### ISSUE TITLE
cannot typecheck program with empty list initializaton

### ISSUE THREAD

**Issue by jplevyak** [exaloop/codon#215] opened 2023-03-12 00:34 UTC
```
def f(a, L=[]):
  L.append(a)
  return L
print(f(1))
print(f(2))
```

python3 returns
[1]
[1, 2]

codon says: "error: cannot typecheck the program"

No only is that not a particularly useful error, this is the sort of type inference which is very useful, e.g. Rust allows the idiom:

let mut vec = Vec::new();
vec.push(1);
vec.push(2);

**Comment by arshajii** [comment] 2023-03-12 13:52
One of the current restrictions/limitations of the type system is that type-checking happens *per-function*, so the external default empty-list argument can't be type checked (@inumanag can explain further).

Note that the general empty list pattern does work, though:

```python
vec = []  # this is deduced to be a list of int
vec.append(1)
vec.append(2)
```

**Comment by inumanag** [comment] 2024-11-08 23:01
If the empty list is later used with instantiated type (in the above example with `int`), that type will be used to deduce the previously unknown item type of the empty list.

**Comment by inumanag** [comment] 2024-11-09 20:27
Duplicate of #334, moving the discussion there.

**Closed by inumanag** 2024-11-09 20:27 UTC
