### ISSUE TITLE
Example on the front page doesn't work

### ISSUE THREAD

**Issue by olegklimov** [exaloop/codon#271] opened 2023-03-19 06:42 UTC
```
import gpu

MAX    = 1000  # maximum Mandelbrot iterations
N      = 4096  # width and height of image
pixels = [0 for _ in range(N * N)]

def scale(x, a, b):
    return a + (x/N)*(b - a)

@gpu.kernel
def mandelbrot(pixels):
    idx = (gpu.block.x * gpu.block.dim.x) + gpu.thread.x
    i, j = divmod(idx, N)
    c = complex(scale(j, -2.00, 0.47), scale(i, -1.12, 1.12))
    z = 0j
    iteration = 0

    while abs(z) <= 2 and iteration < MAX:
        z = z**2 + c
        iteration += 1

    pixels[idx] = int(255 * iteration/MAX)

mandelbrot(pixels, grid=(N*N)//1024, block=1024)
```

I'm running:

`codon build example.py`

The result is:

```
/usr/bin/ld: example.o: in function `std.gpu.Memory._alloc:0[int,int].268':
/home/user/.codon/lib/codon/stdlib/gpu.codon:40: undefined reference to `seq_nvptx_device_alloc'
/usr/bin/ld: example.o: in function `std.gpu.Memory[int]:std.gpu.Memory._write:0[std.gpu.Memory[int],Ptr[int],int].301':
/home/user/.codon/lib/codon/stdlib/gpu.codon:48: undefined reference to `seq_nvptx_memcpy_h2d'
/usr/bin/ld: example.o: in function `std.gpu.Memory._alloc:0[int,Tuple.N2[int,Array[int]]].316':
/home/user/.codon/lib/codon/stdlib/gpu.codon:40: undefined reference to `seq_nvptx_device_alloc'
/usr/bin/ld: example.o: in function `std.gpu.Memory[Tuple.N2[int,Array[int]]]:std.gpu.Memory._write:0[std.gpu.Memory[Tuple.N2[int,Array[int]]],Ptr[Tuple.N2[int,Array[int]]],int].320':
/home/user/.codon/lib/codon/stdlib/gpu.codon:48: undefined reference to `seq_nvptx_memcpy_h2d'
/usr/bin/ld: example.o: in function `std.gpu.Memory[Tuple.N2[int,Array[int]]]:std.gpu.Memory._read:0[std.gpu.Memory[Tuple.N2[int,Array[int]]],Ptr[Tuple.N2[int,Array[int]]],int].554':
/home/user/.codon/lib/codon/stdlib/gpu.codon:44: undefined reference to `seq_nvptx_memcpy_d2h'
/usr/bin/ld: example.o: in function `std.gpu.Memory[int]:std.gpu.Memory._read:0[std.gpu.Memory[int],Ptr[int],int].563':
/home/user/.codon/lib/codon/stdlib/gpu.codon:44: undefined reference to `seq_nvptx_memcpy_d2h'
/usr/bin/ld: example.o: in function `std.gpu.Memory[byte]:std.gpu.Memory._free:0[std.gpu.Memory[byte]].594':
/home/user/.codon/lib/codon/stdlib/gpu.codon:52: undefined reference to `seq_nvptx_device_free'
/usr/bin/ld: example.o: in function `std.gpu.kernel:0.wrapper:0[Tuple.N1[std.internal.types.ptr.List[int]],int,int,Partial.N0.mandelbrot:0[T1][mandelbrot:0,Tuple.N0,KwTuple.N0]].598':
/home/user/.codon/lib/codon/stdlib/gpu.codon:282: undefined reference to `seq_nvptx_function'
/usr/bin/ld: /home/user/.codon/lib/codon/stdlib/gpu.codon:286: undefined reference to `seq_nvptx_invoke'
/usr/bin/ld: example.o: in function `main':
example.py:(.text+0x7cc1): undefined reference to `seq_nvptx_load_module'
collect2: error: ld returned 1 exit status
```

I found that `.codon/lib/codon/stdlib/gpu.codon` contains these symbols, but it's not clear how to link it. Help doesn't have an obvious option. 

So it might be just a usability/discoverability bug. OTOH `import gpu` might add some instruction to link the right thing.

**Comment by arshajii** [comment] 2023-03-20 13:59
Hi @olegklimov -- the pre-built binaries currently don't have the GPU backend enabled (mainly due to dependency issues with CUDA -- we plan to update this soon), so you would have to build Codon from source to enable the GPU backend. Please see https://docs.exaloop.io/codon/advanced/build for instructions (the relevant CMake option is `-DCODON_GPU=ON`), and let me know if you run into any problems.

**Comment by olegklimov** [comment] 2023-03-20 14:17
Aha thank you, clear now. I think a fix for this is to mention "you need to rebuild with cuda support" on the front page.

**Comment by inumanag** [comment] 2024-11-09 19:53
Duplicate of #193, continuing there.

**Closed by inumanag** 2024-11-09 19:53 UTC
