### ISSUE TITLE
Division by zero returned inf

### ISSUE THREAD

**Issue by likecodingloveproblems** [exaloop/codon#404] opened 2023-06-09 21:39 UTC
In python when an integer divided by zero, ZeroDivisionError returned but when the code is compiled by codon the result is inf.
to reproduce bug, you can run the below code.
```
def zero_division():
    print(1 / 0)
zero_division()
```

**Comment by elisbyberi** [comment] 2023-06-09 22:13
Something divided by zero is undefined, `ZeroDivisionError` should be raised.
Something divided by 0 is infinity is the only case when we use limit.

**Comment by elisbyberi** [comment] 2023-06-09 23:25
@likecodingloveproblems Duplicate of #173 See: https://docs.exaloop.io/codon/general/releases#semantics

**Comment by inumanag** [comment] 2023-07-26 13:47
Also: https://docs.exaloop.io/codon/general/differences

**Closed by inumanag** 2023-07-26 13:47 UTC
