### ISSUE TITLE
Cannot build Jupyter plugin on Arch

### ISSUE THREAD

**Issue by NoelJacob** [exaloop/codon#387] opened 2023-05-24 14:49 UTC
```
cmake --build jupyter/build
cmake --install jupyter/build
```
```
[2/144] Building CXX object CMakeFiles/codon_jupyter.dir/jupyter.cpp.o
FAILED: CMakeFiles/codon_jupyter.dir/jupyter.cpp.o
/usr/bin/clang++ -DGUID_LIBUUID -DXEUS_STATIC_LIB -DXEUS_ZMQ_STATIC_LIB -DZMQ_STATIC -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dcodon_jupyter_EXPORTS -I/home/john/Documents/codon/jupyter/. -I/home/john/Documents/codon/jupyter/install/include -I/home/john/Documents/llvm-project/install/include -I/home/john/Documents/codon/jupyter/build/_deps/xeus-src/include -I/home/john/Documents/codon/jupyter/build/_deps/json-src/include -I/home/john/Documents/codon/jupyter/build/_deps/xtl-src/include -I/home/john/Documents/codon/jupyter/build/_deps/xeus-zmq-src/include -I/home/john/Documents/codon/jupyter/build/_deps/cppzmq-src -I/home/john/Documents/codon/jupyter/build/_deps/libzmq-src/include -I/home/john/Documents/codon/jupyter/build/_deps/libzmq-build -pedantic -fvisibility-inlines-hidden -Wno-return-type-c-linkage -Wno-gnu-zero-variadic-macro-arguments -Wno-deprecated-declarations -O3 -std=gnu++17 -fPIC -Wunused-parameter -Wextra -Wreorder -MD -MT CMakeFiles/codon_jupyter.dir/jupyter.cpp.o -MF CMakeFiles/codon_jupyter.dir/jupyter.cpp.o.d -o CMakeFiles/codon_jupyter.dir/jupyter.cpp.o -c /home/john/Documents/codon/jupyter/jupyter.cpp
In file included from /home/john/Documents/codon/jupyter/jupyter.cpp:3:
/home/john/Documents/codon/jupyter/./jupyter.h:4:10: fatal error: 'codon/compiler/jit.h' file not found
#include <codon/compiler/jit.h>
^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[7/144] Building CXX object _deps/xeus-build/CMakeFiles/xeus-static.dir/src/xcomm.cpp.o
ninja: build stopped: subcommand failed.
-- Install configuration: "Release"
CMake Error at jupyter/build/cmake_install.cmake:57 (file):
file INSTALL cannot find
"/home/john/Documents/codon/jupyter/build/libcodon_jupyter.so": No such
file or directory.
```

**Comment by inumanag** [comment] 2023-06-07 19:42
Can you please provide more details: how are you compiling Codon, did you install it with `cmake --install` etc?

**Comment by inumanag** [comment] 2024-11-10 06:09
Duplicate of #152.

**Closed by inumanag** 2024-11-10 06:09 UTC
