### ISSUE TITLE
Front page example not functioning on Mac OS / Linux 

### ISSUE THREAD

**Issue by psytron** [exaloop/codon#565] opened 2024-06-14 16:38 UTC
Example code ( fib.py )
```
def fib(n):
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()
fib(1000)
```
Attempt Commands
```
codon build fib.py
codon build -release fib.py
codon build -release -exe fib.py
```
Result
Linux Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-107-generic x86_64) 
```
error: process for 'g++' exited with status 255
```
Result
Mac OS 11.3.1 MacBook Air Apple Silicon M1
```
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strE
```

**Comment by arshajii** [comment] 2024-06-23 14:38
Hi @psytron -- can you show `g++ --version` please?

**Comment by psytron** [comment] 2024-06-24 15:34
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by inumanag** [comment] 2024-09-23 05:15
Thank you for the report. This is a duplicate of #123; will need to check this in more detail.

**Closed by inumanag** 2024-09-23 05:15 UTC
