### ISSUE TITLE
Is GC turned off in rel V0.16.2?

### ISSUE THREAD

**Issue by dogbert45** [exaloop/codon#446] opened 2023-08-08 13:14 UTC
I end up with a large and continuously increasing memory usage when using codon.
Running the exact same code with python3 I end up with less than 500 Mbyte in the process, and not increasing over time. (Exact except for changing the import statements from 'python import').

But with codon i have to break when the process is going over 20 Gbyte.
There is no tail recursion or strange things going on.

Is the GC turned off in V0.16.2?
In that case is there a way to turn it on?

Or am I missing something very fundamental here?

**Comment by arshajii** [comment] 2023-08-08 13:27
Hi @dogbert45 -- we haven't changed the GC or any of its settings, so what you're seeing is definitely odd. A few questions:

- What system/OS are you running this on?
- Did it work in previous Codon versions?
- Is there any way to create a small example of the issue so we can take a look?

**Comment by dogbert45** [comment] 2023-08-08 13:48
I haven't run this using previous codon releases.
I am using Ubuntu 22.04.03 (64 bit)
Python 3.10.12

I will try to make a small code version which shows the behaviour.

**Comment by inumanag** [comment] 2024-11-10 06:29
Seems to be a duplicate of #472 .

**Closed by inumanag** 2024-11-10 06:29 UTC
