### ISSUE TITLE
error: syntax error, unexpected '('

### ISSUE THREAD

**Issue by starbugs-qurong** [exaloop/codon#321] opened 2023-04-04 10:33 UTC
I have run the following python program program1.py by codon.

class Q625NBX (): 
	TL331N2 = 0.77
	syS0808 = 0.86
	TaiXA3f9 = 28
	HwexU9apV = 7886
	def oDt49nu52 ( self ) -> bool : 
			self.TL331N2/=(1if((1if(self.syS0808==0)else(self.syS0808))==0)else((1if(self.syS0808==0)else(self.syS0808))))  
if __name__ == '__main__':
	TvL82v3Nc= Q625NBX();
	TvL82v3Nc.oDt49nu52()
	print(TvL82v3Nc.TL331N2)
	print(TvL82v3Nc.syS0808)
	print(TvL82v3Nc.TaiXA3f9)
	print(TvL82v3Nc.HwexU9apV)

And it output error message as follow:
codon_program1.py:7:22: error: syntax error, unexpected '('

I hava run it by both python3 and pypy3 and output the following content:
0.8953488372093024
0.86
28
7886

The related files can be found in https://github.com/starbugs-qurong/python-compiler-test/tree/main/codon/python_1

**Comment by elisbyberi** [comment] 2023-04-04 10:52
@starbugs-qurong Same as in #320, declare member type:
``` python
class Q625NBX:
    TL331N2: float = 0.77
    syS0808: float = 0.86
    TaiXA3f9: int = 28
    HwexU9apV: int = 7886
```

**Comment by starbugs-qurong** [comment] 2023-04-11 08:51
I have declared member types but still meet this error: program1.py:7:22:  error: syntax error, unexpected '('
`class Q625NBX: 
	TL331N2:float = 0.77
	syS0808:float = 0.86
	TaiXA3f9:int = 28
	HwexU9apV:int = 7886
	def oDt49nu52 ( self ) -> bool : 
			self.TL331N2/=(1if((1if(self.syS0808==0)else(self.syS0808))==0)else((1if(self.syS0808==0)else(self.syS0808))))  
if __name__ == '__main__':
	TvL82v3Nc= Q625NBX();
	TvL82v3Nc.oDt49nu52()
	print(TvL82v3Nc.TL331N2)
	print(TvL82v3Nc.syS0808)
	print(TvL82v3Nc.TaiXA3f9)
	print(TvL82v3Nc.HwexU9apV)`

**Comment by starbugs-qurong** [comment] 2023-04-11 09:07
I have declared the member types and run it again, the error "unexpected '(' " still exist. 

The related files can be found in https://github.com/starbugs-qurong/python-compiler-test/tree/main/codon/python_1

**Comment by elisbyberi** [comment] 2023-04-11 17:31
@starbugs-qurong Duplicate of #317

**Comment by inumanag** [comment] 2024-11-09 20:23
Oh, Codon does not like `if/else` without spaces before the keywords. Thank you for the report—this is bug on our side.

**Closed** 2024-11-26 17:54 UTC
Labels: bug
