### ISSUE TITLE
Bug Report: libc++abi error when using python decorator

### ISSUE THREAD

**Issue by bw-xu** [exaloop/codon#138] opened 2022-12-28 14:51 UTC
### Environment

MacOS 13.1, Python 3.8.3/3.11.0, codon 0.15, codon-jit

### Description

After I installed `codon` via `/bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"`, I can run `.py` file correctly via `codon run -release fib.py`. However, when I tried the [python decorator](https://docs.exaloop.io/codon/interoperability/decorator), it says 

>  libc++abi: terminating with uncaught exception of type codon::exc::ParserException: cannot locate standard library

The code I ran is 

```Python
import codon
from time import time

def is_prime_python(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

@codon.jit
def is_prime_codon(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

t0 = time()
ans = sum(1 for i in range(100000, 200000) if is_prime_python(i))
t1 = time()
print(f'[python] {ans} | took {t1 - t0} seconds')

t0 = time()
ans = sum(1 for i in range(100000, 200000) if is_prime_codon(i))
t1 = time()
print(f'[codon]  {ans} | took {t1 - t0} seconds')
```

**Comment by arshajii** [comment] 2022-12-28 15:34
Will be fixed in next release, but for now you can set the `CODON_PATH` environment variable to the standard library path (`~/.codon/lib/codon/stdlib` by default). For example, for me it would be:

``` bash
export CODON_PATH=/Users/arshajii/.codon/lib/codon/stdlib
```

**Comment by bw-xu** [comment] 2022-12-30 14:15
Thanks for replying! I tried that, and it seemed to work. However, another error occurs in line 13 (`def is_prime_codon(n):`)

> Exception has occurred: UnicodeEncodeError
> 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)

**Comment by bw-xu** [comment] 2022-12-30 15:42
> Thanks for replying! I tried that, and it seemed to work. However, another error occurs in line 13 (`def is_prime_codon(n):`)
> 
> > Exception has occurred: UnicodeEncodeError
> > 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)

This is the full traceback info:

> Traceback (most recent call last):
>   File "/Users/bowenxu/Codes/Codon学习/foo1.py", line 12, in <module>
>     @codon.jit
>      ^^^^^^^^^
>   File "/opt/homebrew/Caskroom/miniforge/base/envs/Crypto/lib/python3.11/site-packages/codon/decorator.py", line 217, in jit
>     return _decorate(fn)
>            ^^^^^^^^^^^^^
>   File "/opt/homebrew/Caskroom/miniforge/base/envs/Crypto/lib/python3.11/site-packages/codon/decorator.py", line 187, in _decorate
>     _jit.execute(
>   File "codon/jit.pyx", line 27, in codon.codon_jit.JITWrapper.execute
>   File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)

**Comment by bw-xu** [comment] 2022-12-30 15:46
OH, I know the reason. This is because my path to the source file contains Unicode characters. If there aren't such characters, [the solution above](https://github.com/exaloop/codon/issues/138#issuecomment-1366738628) works.

**Comment by inumanag** [comment] 2023-01-04 01:46
@bw-xu Thanks for the report. Will see if we can handle this.

**Comment by bw-xu** [comment] 2023-01-04 01:52
> @bw-xu Thanks for the report. Will see if we can handle this.

Let's see.

Also, I wonder if there is any guide for developer who would like to contribute to this project.

I feel like codon is a fancy project, and I hope to fix bugs and improve it if I could.

**Comment by inumanag** [comment] 2024-11-08 18:57
Duplicate of #128; will move the discussion there.

**Closed by inumanag** 2024-11-08 18:57 UTC
Labels: bug
