### ISSUE TITLE
Windows prebuilt binaries, please

### ISSUE THREAD

**Issue by ManiArasteh** [exaloop/codon#589] opened 2024-09-09 07:56 UTC
Please add Windows prebuilt binaries

**Comment by elisbyberi** [comment] 2024-09-09 11:30
See #69

**Comment by ManiArasteh** [comment] 2024-09-09 11:34
Ok, I saw. Now what? I was trying to compile but it failed. Now I don't have MSVC.

**Comment by elisbyberi** [comment] 2024-09-09 13:39
> Ok, I saw. Now what?

Comprehend!

**Comment by ManiArasteh** [comment] 2024-09-16 16:00
You Comprehend!

**Comment by ManiArasteh** [comment] 2024-09-16 16:00
And you're not the owner/contributor of Codon

**Comment by elisbyberi** [comment] 2024-09-16 19:29
@ManiArasteh Codon is open source, and contributions toward making it possible to compile Codon on Windows are welcome. First, please note that this issue is a duplicate of #69. Additionally, issue #403 is tracking native Windows support, which aims to enable prebuilt binaries.

> What? I don't know.

If you're unsure about the current situation, please feel free to ask specific questions in the [Discussions](https://github.com/exaloop/codon/discussions) section.

For more information, see: https://exaloop.io/.

**Comment by ManiArasteh** [comment] 2024-09-17 20:53
Ok. But I failed to compile. If I compiled successfully, I contribute this project. It has a bug.
And for users who are on Linux,
Your OS even not having Microsoft Office! Just some programming languages and a garbage office tool called LibreOffice.
Even MS Office cannot be installed with Wine
_I don't know why everyone are migrating to Linux? Even in Iran, where only 5%-10% of people are programmer_

**Comment by ManiArasteh** [comment] 2024-09-21 07:37
I don't like to install Linux. I need Microsoft Office and Windows 11 is not as garbage as you say. Even it is very, very, very better than a Linux distribution.

**Comment by ManiArasteh** [comment] 2024-09-21 07:37
And I said Codon for Windows, not Linux = garbage

**Comment by aguspiza** [comment] 2024-09-21 08:30
> And I said Codon for Windows, not Linux = garbage. Please help me.

Use WSL2 in your beautiful Windows.

**Comment by ManiArasteh** [comment] 2024-09-21 08:32
Yep, In my beautiful Windows. I want to use it without WSL2. I know how to do it with WSL. 
1. I don't have many disk space left. 
2. If I want, I use in that.

**Comment by aguspiza** [comment] 2024-09-21 08:40
@ManiArasteh This is opensource, if you really, really, really want to compile without WSL2, make it happen and do a PR with the changes.

WSL2 with the whole build system with probably use much less space that Windows itself, and with VSCode integration, you barely notice that you are really using Linux.

**Comment by ManiArasteh** [comment] 2024-09-21 08:43
Nope. I'm using Windows, and I have only -1 GB of storage. I said build failed, but you're saying open a PR

**Comment by ManiArasteh** [comment] 2024-09-21 08:43
Hey! Maybe I can do it with MinGW.

**Comment by aguspiza** [comment] 2024-09-21 08:44
> Nope. I'm using Windows, and I have only -1 GB of storage. I said build failed, but you're saying open a PR

🤣 You won't be able to install any Windows updates.

**Comment by ManiArasteh** [comment] 2024-09-21 08:45
:) :joy:

**Comment by ManiArasteh** [comment] 2024-09-21 15:38
> if u feel bad bout Linux, don't create any issues on project that supporting them instead of windows
@cuynu At least I don't have problem with Mac. MacOS is a better Linux.

**Comment by inumanag** [comment] 2024-09-23 04:38
Please see #69.

**Closed by inumanag** 2024-09-23 04:38 UTC
