### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by jschwar313** [exaloop/codon#266] opened 2023-03-18 10:51 UTC
When will codon be supported under windows?  Are there plans for this?

**Comment by HenrYxZ** [comment] 2023-03-18 15:57
I'm trying to use it in Ubuntu inside Windows through WSL2 but it says:

```
Command 'codon' not found, did you mean:

  command 'codonw' from deb codonw (1.4.4-4)

Try: sudo apt install <deb name>
```

I tried opening and closing the terminal and even rebooting my PC

**Comment by jschwar313** [comment] 2023-03-18 16:29
This issue is asking for support on a Windows machine running python, not windows running a UNIX version.

**Comment by xlbljz** [comment] 2023-03-20 09:29
I guess windows is total different from linux. It may need much more work to do.

**Comment by TemporalClepsydra** [comment] 2023-05-12 16:46
what exactly in the code would need to be changed?

**Comment by elisbyberi** [comment] 2023-05-12 17:11
Marking as duplicate of #69

**Comment by inumanag** [comment] 2023-06-09 17:34
See #69.

**Closed by inumanag** 2023-06-09 17:34 UTC
