### ISSUE TITLE
Any pre-built binaries for Linux (x86_64) with CUDA enabled for downloading?

### ISSUE THREAD

**Issue by tongzhou80** [exaloop/codon#522] opened 2023-12-29 19:38 UTC
As far as I understand, this has no CUDA support:

```
/bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"
```

I tried to build the source by myself, but got many cmake errors, and thought it'll be great if there's pre-built binaries for linux+x86_64 now. Thanks!

**Comment by inumanag** [comment] 2024-11-10 19:12
Duplicate of #193.

**Closed by inumanag** 2024-11-10 19:12 UTC
Labels: dependencies
