### ISSUE TITLE
pip3 install codon-jit error  is valid for C/ObjC but not for C++

### ISSUE THREAD

**Issue by yincangshiwei** [exaloop/codon#128] opened 2022-12-23 06:06 UTC
cc1plus: 警告：command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [默认启用]
      In file included from codon/jit.cpp:765:0:
      /root/.codon/include/codon/compiler/jit_extern.h: 在静态成员函数‘static codon::jit::JITResult codon::jit::JITResult::error(const string&)’中:
      /root/.codon/include/codon/compiler/jit_extern.h:19:64: 错误：‘nullptr’在此作用域中尚未声明
         static JITResult error(const std::string &message) { return {nullptr, message}; }
                                                                      ^
      /root/.codon/include/codon/compiler/jit_extern.h:19:80: 错误：could not convert ‘{<expression error>, message}’ from ‘<brace-enclosed initializer list>’ to ‘codon::jit::JITResult’
         static JITResult error(const std::string &message) { return {nullptr, message}; }
                                                                                      ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for codon-jit
![image](https://user-images.githubusercontent.com/8185843/209281335-fe49cd46-fdd5-4f7b-974f-27bb22229956.png)

**Comment by inumanag** [comment] 2023-01-04 01:40
Hi @yincangshiwei 

This seems to be an issue with Cython or your Python environment—we do not use this flag at all. Which OS/Python distro this is, please?

**Comment by yincangshiwei** [comment] 2023-01-29 06:53
> Hi@yincangshiwei
> 
> This seems to be an issue with Cython or your Python environment—we do not use this flag at all. Which OS/Python distro this is, please?

win10 system.python version 3.85

**Comment by Jong-hun-Park** [comment] 2023-02-16 18:54
Same issue here

**Comment by yincangshiwei** [comment] 2023-03-16 03:09
@inumanag

**Comment by clevey** [comment] 2023-03-21 05:47
try to update your gcc/g++ version.
when i use default gcc 5.4 of ub16, same error appear. 
after upgrade gcc to version 9 and set to /usr/bin default gcc softlink, install success.

**Comment by inumanag** [comment] 2024-11-08 18:57
Duplicate of #128; will move the discussion there.

**Closed by inumanag** 2024-11-08 18:57 UTC
