### ISSUE TITLE
How do I install Codon Jupyter plugin

### ISSUE THREAD

**Issue by NoelJacob** [exaloop/codon#371] opened 2023-04-30 19:56 UTC
```
> codon jupyter
Jupyter support not included. Please install Codon Jupyter plugin.

```
I didn't even know a plugin system was available.

**Comment by elisbyberi** [comment] 2023-05-05 22:47
@NoelJacob Have you tried https://docs.exaloop.io/codon/interoperability/jupyter

**Comment by NoelJacob** [comment] 2023-05-13 12:53
> @NoelJacob Have you tried https://docs.exaloop.io/codon/interoperability/jupyter

Creating the kernel file and choosing it gives the same output that plugin isn't installed.

**Comment by elisbyberi** [comment] 2023-05-13 19:09
@NoelJacob Sorry, I meant to post this link instead: https://docs.exaloop.io/codon/advanced/build#jupyter-support
Sleep deprivation is taking its toll on me.

**Comment by elisbyberi** [comment] 2023-05-13 20:11
@arshajii Would it be helpful to include a link to the [jupyter-support](https://docs.exaloop.io/codon/advanced/build#jupyter-support) section in the https://docs.exaloop.io/codon/interoperability/jupyter page?

**Comment by arshajii** [comment] 2023-05-14 15:36
Thanks -- we'll update these docs soon.

**Comment by NoelJacob** [comment] 2023-05-23 18:21
It'd be cool if you distribute binaries with Jupyter support

**Comment by dbonner** [comment] 2023-12-23 12:27
Hi all,
I've absolutely failed to build the Jupyter plugin using the latest source code and following the above instructions diligently.
I was able to build codon from the latest source code with no problem.
Cheers,
Daniel

**Comment by inumanag** [comment] 2024-11-10 06:06
Duplicate of #152—will track the progress there.

**Closed** 2024-11-10 06:06 UTC
