### ISSUE TITLE
Can Codon support big integer computation directly？Ten thousand positive integers

### ISSUE THREAD

**Issue by ewwerpm** [exaloop/codon#238] opened 2023-03-15 07:05 UTC
这个Codon，支持直接大整数计算吗？成千上万位的整数乘法。 我已经知道taichi、numba都不直接支持大整数乘法了。

**Comment by arshajii** [comment] 2023-03-17 14:39
Hi @ewwerpm -- Codon supports larger bit-width integers, as shown in https://docs.exaloop.io/codon/language/extra#arbitrary-width-integers. There's no true arbitrary-width int type in the standard library yet, but it's something that will probably be added in the future.

**Comment by inumanag** [comment] 2024-11-08 18:52
Duplicate of #235.

**Closed by inumanag** 2024-11-08 18:52 UTC
