### ISSUE TITLE
Homebrew and other package manager support

### ISSUE THREAD

**Issue by codeyash** [exaloop/codon#407] opened 2023-06-13 03:55 UTC
Homebrew support and other package manage based installation is missing. Please add support!

**Comment by arshajii** [comment] 2023-06-13 21:36
Hi @codeyash -- this is on our TODO list. We'll try to get to it ASAP!

**Comment by inumanag** [comment] 2024-11-10 06:15
Duplicate of #77 .

**Closed by inumanag** 2024-11-10 06:15 UTC
