### ISSUE TITLE
error: unexpected dedent

### ISSUE THREAD

**Issue by starbugs-qurong** [exaloop/codon#329] opened 2023-04-04 10:48 UTC
I have run the following python program program10.py by codon.

class ZgM3gNx202 (): 
	q1Z69u23 = 31
	def eih319224 ( self )  : 
			u0r65y5c8 = 6960 
			self.q1Z69u23/=(1if((1if(self.q1Z69u23==0)else(self.q1Z69u23))==0)else((1if(self.q1Z69u23==0)else(self.q1Z69u23)))) ; 
if __name__ == '__main__':
	po0hER8fZ= ZgM3gNx202();
	po0hER8fZ.eih319224()
	print(po0hER8fZ.q1Z69u23)

And it output error message as follow:
codon_program10.py:5:1: error: unexpected dedent

I hava run it by both python3 and pypy3 and output the following content:
1.0

The related files can be found in https://github.com/starbugs-qurong/python-compiler-test/tree/main/codon/python_10

**Comment by elisbyberi** [comment] 2023-04-04 11:42
@starbugs-qurong Same as in #322, and you can not change class member type. You have to declare it as float, if you are going to set its value to a float.
``` python
class ZgM3gNx202():
    q1Z69u23: float = 31.0
```

**Comment by starbugs-qurong** [comment] 2023-04-11 10:50
Thank you. I have made modifications to the program based on your suggestions,  and the error "unexpected dedent" still exist. 

The related files can be found in https://github.com/starbugs-qurong/python-compiler-test/tree/main/codon/python_10

**Comment by elisbyberi** [comment] 2023-04-11 17:30
@starbugs-qurong Duplicate of #317

**Comment by inumanag** [comment] 2023-07-26 21:19
This is certainly a bug in parser.

**Comment by inumanag** [comment] 2024-11-09 20:25
Duplicate of #321: space issue again! Thank you for these @starbugs-qurong

**Closed by inumanag** 2024-11-09 20:25 UTC
Labels: bug
