### ISSUE TITLE
typing.Tuple[int] fails codon when it is taken as a base class

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#253] opened 2023-03-16 23:46 UTC
In the following example, typing.Tuple[int] fails codon when it is taken as a base class of C

test.py:
```
from typing import Tuple
a = Tuple[int]   # work well
class C(Tuple[int]):   # aborted
	pass
```

Reproduce:
'codon/codon-linux-x86_64/codon-deploy/bin/codon' run -release test.py

Crash message:
```
Assert failed:	'Tuple.N1' has no non-canonical name
Expression:	false
Source:		/github/workspace/codon/parser/cache.cpp:32
Aborted (core dumped)
```

Behavior on CPython 3.10.8: work well

Environment:
codon: v0.15.5 on Feb 6
Ubuntu 18.04

**Comment by inumanag** [comment] 2023-03-26 00:44
This is duplicate of #169--- the inheritance mechanism needs major refactoring to support this for now.

Also: inheritance is not supported on Tuples and `@tuple` classes for now.

**Closed** 2023-03-26 00:45 UTC
