### ISSUE TITLE
Forward references

### ISSUE THREAD

**Issue by matthew-parrott** [exaloop/codon#480] opened 2023-09-12 00:26 UTC
Hi there -- does Codon support forward references as defined in PEP 484:

https://peps.python.org/pep-0484/#forward-references

I have some code which looks like this:

```
class A:
    child: 'A' = None
```

But, I get the error:
`error: expected type expression`

**Comment by matthew-parrott** [comment] 2023-09-12 00:32
It looks like this works:

```
class A:
    child: A = None
```

Which, I'm happy there's a way to do this. But, that means the code won't work in Python and I was hoping (maybe unrealistically so) that I could run the same code (within reason; it has 0 dependencies outside the standard library) in both environments.

**Comment by inumanag** [comment] 2024-01-29 19:48
This is duplicate of [#482 ](https://github.com/exaloop/codon/issues/507); `Self` should be the canonical way to cover both grounds.

**Closed by inumanag** 2024-01-29 19:48 UTC
